### ISSUE TITLE
Infill for the airfoil

### ISSUE THREAD

**Issue by aapolipponen** [aapolipponen/fullcontrol-airfoil#1]
After the airfoil lofting is working again it would probably be nice to add some kind of infill. Real airplane wings use hexagons so that could be cool.

**Comment by fullcontrol-xyz** [comment]
This is a valuable function for FullControl in general. For typical wings, are the hexagons form-fitted - i.e. the hexagons shapes and sizes morph to fit the airfoil shape as neatly as possible - or are they more like the airfoil shape is cut out from a simple hexagon lattice, leaving partial unit cells at all edges?

Not related to hexagons, but a very simple filling strategy would be this: 
![image](https://user-images.githubusercontent.com/129191348/233978957-2af29075-a66e-4254-949e-bf1c54583aa2.png)

The curved waves could be replaced with triangle waves, and there could be several rows of waves instead of just two, as shown the image above. It would be simple to design and allow to a travel-free print-path that would easily fit within a customised vase-mode strategy. It also readily allows grading to be stiffer/stronger in different regions, either with unit-cell-shapes/size or with customised varying extrusion width (e.g. like the CONVEX research study: [video](https://www.youtube.com/watch?v=2Lkt4ZxSZhk&ab_channel=AndyGleadall), [paper](https://www.researchgate.net/publication/346098541)).

**Comment by fullcontrol-xyz** [comment]
All sounds good. Adding a few solid-filled layers every once in a while should be easy. And length-wise spars may not be necessary if this infill runs continuously all the way. A more unusual option would be do unsupported overhangs (like the FullControl Overhang Challenge) since the geometry is appropriate for that. This would achieve the ribs independently of the spars and avoid the need for any infill if it's not required for mechanical purposes. I'm definitely not an airfoil person so let's see what other more informed people suggest for the functional requirements and I can comment on potential toolpaths

**Comment by aapolipponen** [comment]
The spars could be something like carbon fiber. That make's the wing not fully 3d printed but the wing has a lot more strenght. I think for many people that could be useful so it should be an option in the future. Also then the infill can be reduced an making the wing is faster. The unsupported overhangs sound like they make sense. Still the fully 3d printed wing also should be very well supported in the software. For now I really encourage you to contribute. My school work makes it that some days I have a lot of time and on ther days pretty much none.

**Comment by fullcontrol-xyz** [comment]
I afraid won't be able to contribute significantly since I have to focus my efforts on the main FullControl repo. And similarly, very little free time! This is something I'll keep an eye on but its not directly related to my research/teaching so it isn't going to be something I can do much on. If a growing community establishes here, I may be able to do more technical things

**Comment by aapolipponen** [comment]
That's ok. I posted about this to the subreddit and am going to post into r/3dprinting too to get some people contributing. I don't want to pressure anyone.

**Comment by fullcontrol-xyz** [comment]
Cool. Don't worry, not pressured. I love your enthusiasm!

**Comment by aapolipponen** [comment]
![image](https://user-images.githubusercontent.com/47327885/235930531-9ba092b4-b221-4e97-ad2e-c10a41054541.png)
First prototype for the infill. I didn't get the hexagon infill to work so here's your idea. I am going to implement the symmetry down the middle soon. I think I am going to commit the system in a few days. This issue will still be open because I don't think the infill system is even nearly done.

**Comment by aapolipponen** [comment]
The density is adjustable. For this picture the density is 64 which is quite high.
![image](https://user-images.githubusercontent.com/47327885/235931747-350f0209-08f0-4b5a-922d-e0cfc6d83704.png)
Here's one using 24.
![image](https://user-images.githubusercontent.com/47327885/235931998-38abba7e-d852-4a1d-ab44-e72454720f02.png)
Here's one using 8.

**Comment by aapolipponen** [comment]
Committed the system to Infill_dev branch.

**Comment by aapolipponen** [comment]
![IMG_20230507_100043.jpg](https://user-images.githubusercontent.com/47327885/236662938-3feff524-2e5c-46fa-9a0d-4fa105528dbd.jpg)

Did a test print. Everything seems to work correctly. The vertical line is the printer traveling to 0,0 to go to the next layer. Surprisingly there doesn't seem to be issues with it colliding with the infill. Pushing to main soon.

**Comment by aapolipponen** [comment]
Also the speeds need to be somewhat lower for this. The airfoil prints without infill are much easier to print fast.

**Comment by fullcontrol-xyz** [comment]
These are looking great. For the triangle-wave infill, you could return to the origin by printing a flipped version of the tri-wave back to the start point immediately after the current tri-wave. This means you'll print two waves and they'll always cross each other along the middle-axis. Sometimes we print with a half-layer-offset in z between the two halves of the infill. This means the second tri-wave is slightly higher and the crossing points between the two waves become nicely symmetrical ([associated journal paper](https://www.sciencedirect.com/science/article/pii/S2214785322057212))

**Comment by aapolipponen** [comment]
The double tri-wave and reinforced circles are now done. Can you help me understand what you mean by the half-layer-offset in z? Is it for the layers to adhere better?

**Comment by fullcontrol-xyz** [comment]
I mean, if layer height is 0.2 mm, you can print the first zigzag line (out) at the current Z value, then the second zigzag line (return) with Z increased by 0.1 mm. Then the jump up to start the next 'layer' will only need to be 0.1 mm to achieve an actual layer height of 0.2 mm

**Comment by aapolipponen** [comment]
Ok, now I understand. I will look into implementing that.

**Comment by aapolipponen** [comment]
Closing this issue and creating a new issue for new infill patterns.
