### ISSUE TITLE
Question: what's this project's aim?

### ISSUE THREAD

**Issue by AndyGlx** [aapolipponen/fullcontrol-airfoil#2]
Hi, it's fascinating to see FullControl be used for this! What's the overall aim of the work/research? It is just for experimenting or are there larger ambitions?

**Comment by aapolipponen** [comment]
At first, the idea was just playing around with the airfoil generation. So the project started as a personal project. I saw someone do a post or a comment in the subreddit that airfoils are possible in the excel version. Then I thought that they could work in the python version too. So I did some prototyping got some airfoils to generate and then thought about doing a loft between them and making improvements. And here we are now. I think the project should be an open source way for rc hobbyists and makers to create wings / airfoils using 3d printing. I don't know the licenses for this stuff but right now I think people can suggest additions to this project and use the project non-commercially. I will put a license for this pretty soon, say if you have ideas for which license I should use. I don't know about the commecrcial usage, or what I should do about that. But that isn't a problem right now. Reopen the issue if you have any questions or want to suggest a license.

**Comment by aapolipponen** [comment]
I remembered that you can't reopen issues so I reopened this issue. If I don't see any comments for a few days then I will close this again.

**Comment by fullcontrol-xyz** [comment]
I think it'd be great if this became a hub where people could collaborate and develop this stuff. There are lots of interesting challenges. Attachment of the airfoil to the main body is one. I'm considering that as a demo... to print the 'bottom' of the airfoil on a nonplanar printed substrate (instead of the print bed) so that it fits the curved form of the aircraft body. 
In terms of a licence, I'd recommend going fully open source to encourage as many people to support as possible. I looked into licences a bit and decided GNU GPL3 is good. So if you're not sure at all and don't want to investigate the options, you could just go with that

**Comment by aapolipponen** [comment]
I'm going to go with GNU GPL3. I'm closing this issue.
