### ISSUE TITLE
Readme images (when project is complete) 

### ISSUE THREAD

**Issue by fullcontrol-xyz** [aapolipponen/fullcontrol-airfoil#6]
When things seem like they're not got to change too much going forwards, it'd be great if the readme had images of the various neat things you've done here. Many of those are more valuable and considered than may be apparent to a new visitor to the repo. E.g. The aspects of the toolpath with no travel (it's much better than regular space-filling infill). But you don't want to out effort on this if the images will be invalidated by upcoming commits. So, no rush

**Comment by aapolipponen** [comment]
Oh yea, the documentation can be improved a lot. Easiest way to understand the system is mostly just to read the comments in the code. I will probably just rewrite the README.md and then improve the documentation from there. Right now probably is a good point to start documenting things. The structure is pretty solid because its been kind of my main focus to get things to a solid point and build in some modularity for example for the infill system. I will add this to the top of the todo list.
